# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gox < Formula
  desc "JSX-like syntax for Go"
  homepage "https://github.com/germtb/gox"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/germtb/gox/releases/download/v0.1.1/gox_darwin_amd64.tar.gz"
      sha256 "a04a49bdfcc2cee2cf2d3f952eb4bd973062b06182e2416c6e9614fba68601df"

      def install
        bin.install "gox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/germtb/gox/releases/download/v0.1.1/gox_darwin_arm64.tar.gz"
      sha256 "7def4006a540c98cab3c17cb85f3f212a0727df78fed762db06e5feb762683af"

      def install
        bin.install "gox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/germtb/gox/releases/download/v0.1.1/gox_linux_amd64.tar.gz"
      sha256 "48c65601186890a01698c8594f09c09fc8f11ef2365d7337a5ca189bc7dc7f5b"
      def install
        bin.install "gox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/germtb/gox/releases/download/v0.1.1/gox_linux_arm64.tar.gz"
      sha256 "f56ca14eb0f41bc243f69e980a8020124bf1b1221dd02df1ae9ab7d5f3e59db0"
      def install
        bin.install "gox"
      end
    end
  end

  test do
    system "#{bin}/gox", "version"
  end
end
