# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gox < Formula
  desc "JSX-like syntax for Go"
  homepage "https://github.com/germtb/gox"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/germtb/gox/releases/download/v0.1.4/gox_darwin_amd64.tar.gz"
      sha256 "d6837e73d6ca8db403b55cad9f164f6994ae86aae9da4ff25b3c51fd3954a56c"

      def install
        bin.install "gox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/germtb/gox/releases/download/v0.1.4/gox_darwin_arm64.tar.gz"
      sha256 "90a3d7cb8a790c3f51db377c17f381b2f62863bba927f92af66fa729129b6df7"

      def install
        bin.install "gox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/germtb/gox/releases/download/v0.1.4/gox_linux_amd64.tar.gz"
      sha256 "34c97242722d05b063dce8d0b9ca4fc7ee3212bcc1dc1f39faae39a7d1714720"
      def install
        bin.install "gox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/germtb/gox/releases/download/v0.1.4/gox_linux_arm64.tar.gz"
      sha256 "aafb919c3a92e5356c2677faf9acacb6d614a8f260cd1c73b8bd9292bde8ff82"
      def install
        bin.install "gox"
      end
    end
  end

  test do
    system "#{bin}/gox", "version"
  end
end
